### ISSUE TITLE
Create Atlantis groups file with SVSPP/NESPP codes

### ISSUE THREAD

**Issue by gambler1650** [NOAA-EDAB/atneus_RM#12]

**Comment by RMORSEcode** [comment]
check out coderelations.csv in the R/ folder for a start

**Comment by RMORSEcode** [comment]
There is also this, but it looks incomplete and V1.0 based rather than v1.5
[https://github.com/NOAA-EDAB/atneus_RM/blob/master/specieslist_v15.csv](url)

**Comment by gambler1650** [comment]
Completed... Posted here as I don't want to muddy the waters in the reorganization at the moment..
[https://github.com/NOAA-EDAB/Atlantis-Catch-Files/blob/master/Atlantis_1_5_groups_svspp_nespp3.csv](url)
