### ISSUE TITLE
Determine time period for hindcast comparisons

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/atneus_RM#7]
This is [point 3 for review criteria](https://github.com/NOAA-EDAB/atneus_RM/wiki).

Ideally this is a time period we have survey/assessment time series with error bounds, and also the other data for comparisons (age/lengths, diets, possibly spatial data)

**Comment by slarge** [comment]
Proposals:
* 1990 (ish) - 2010
    + CON: We can't reliably do trends in less than 30 years.
    + PRO: They implemented some management changes that might cause some issues (Rob can explain further)
* 1980-2010
    + CON: Might have survey differences over time, potential Albatross/Bigelow conversion issue
    + PRO: Thirty years so we *can* determine trends, can use SOE timeseries, 
* 1964-2008
    + CON: ?
    + PRO: Full dynamics/history that the assessments are trying to capture, miss Albatross/Bigelow conversion issues
* Hybrid (trend matching with long timeseries + population from shorter/recent timeseries) 
    + CON: ?
    + PRO: ?
Others?

Characteristics we're trying to capture:
1. Snapshot of population growth/ productivity 
2. Time trends match

**Comment by sgaichas** [comment]
See discussion in [meeting minutes for Oct 2 2019](https://github.com/NOAA-EDAB/atneus_RM/wiki/Meeting-minutes#20191002).

Group decision is to use the hybrid approach, with 1980-2010 for hindcast comparisons (to start after 20 years of model spinup). Population productivity comparisons will be for a current snapshot (approximately 2005-2010), not required to get changes over time.
